spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 150666
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.sxsduki.blog: info
  file: log/blog-pro.log
server:
  port: 8800

